[providers]
node = "20"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = [
  "npm ci --production=false",
  "npm run build"
]

[phases.start]
cmd = "node build/index.js"