[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.build]
cmds = [
  "npm ci --production=false",
  "npm run build"
]

[phases.start]
cmd = "node build"