[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["node"]

[deploy]
startCommand = "node build/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NODE_VERSION = "20"